sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@latest -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm run build
  - sonar-scanner -Dsonar.projectKey=webstation-front -Dsonar.organization=creatingsolutions-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c8e6fb27c5bb11d34fc24168bb0a0881087faacc
